### PR TITLE
Replace debugger with Byebug and update pry dependency to 0.10.1

### PR DESCRIPTION
**Pull request by h35514n**
Debugger doesn't work with Ruby 2.x and the current version of Pry is 0.10.1. 
Users are reporting dependency conflicts with other gems that depend on the current version of Pry.

### CODE REVIEW

**Comment by ashaninBenjamin** [comment]
+1

**Comment by mhenrixon** [comment]
:+1:

**Comment by hbin** [comment]
:+1:

**Comment by aried3r** [comment]
Been using this for a few weeks now, works without a problem for me. Thanks for the effort.

Added to my Gemfile like this, for anyone who wants to copy and paste:

``` Ruby
group :development do
  gem 'jazz_hands',                   # Make rails console a lot better
    github: 'jkrmr/jazz_hands',       # Fork that has pry 0.10.0
    branch: 'byebug_and_updated_pry'  # Needed so we can use pry-byebug
end
```

**Comment by carlosplusplus** [comment]
This is amazing, thank you so much @jkrmr! :+1: 
Big fan of jazz-hands, glad to see this was done.

**Comment by h35514n** [comment]
Hi all, 

Just a head's up that I have an updated fork of the gem (v 1.0.0) [here](https://github.com/jkrmr/jazz_hands), which you can install using 

``` ruby
group :development, :test do
  gem 'jazz_hands', github: 'jkrmr/jazz_hands'
end
```

or, if you're not using bundler,

``` bash
$ gem install specific_install
$ gem specific_install jkrmr/jazz_hands
```

Hopefully this'll relieve some headaches. Cheers :)

**Comment by aried3r** [comment]
Awesome, any plans to put it on rubygems.org in case @nixme does not want to further maintain this?

**Pull request closed without merging**
